
services:
  backend:
    build: .
    container_name: scrna-backend
    volumes:
      - ./uploads:/app/uploads
      - ./figures:/app/figures
    command: ["python", "src/main.py"]

  frontend:
    build: .
    container_name: scrna-frontend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./figures:/app/figures
    command: ["shiny", "run", "--port", "8000", "UI/anikaapp.py"]
    depends_on:
      - backend
