
services:
  backend:
    build: .
    container_name: scrna-backend
    volumes:
      - ./data:/app/data
    command: ["python", "src/main.py"]

  frontend:
    build: .
    container_name: scrna-frontend
    ports:
      - "8000:8000"
    command: ["shiny", "run", "--port", "8000", "UI/app.py"]
    depends_on:
      - backend
